export const LOAD_CARD_REQUEST = "LOAD_CARD_REQUEST";
export const LOAD_CARD_SUCCESS = "LOAD_CARD_SUCCESS";
export const LOAD_CARD_FAILURE = "LOAD_CARD_FAILURE";

export const ADD_CARD_REQUEST = "ADD_CARD_REQUEST";
export const ADD_CARD_SUCCESS = "ADD_CARD_SUCCESS";
export const ADD_CARD_FAILURE = "ADD_CARD_FAILURE";

export const LOAD_PAYMENTS_REQUEST = "LOAD_PAYMENTS_REQUEST";
export const LOAD_PAYMENTS_SUCCESS = "LOAD_PAYMENTS_SUCCESS";
export const LOAD_PAYMENTS_FAILURE = "LOAD_PAYMENTS_FAILURE";

export const DELETE_CARD = "DELETE_CARD";